site_name: DrivingApp
site_url: https://drivingapp.readthedocs.io
repo_url: https://github.com/smartsdkCenidet/DrivingApp-docs/
site_description: DrivingApp Documentation
docs_dir: doc/
theme: readthedocs
markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_core.css"]
edit_uri: 'edit/master/doc/'
pages:
  - Inicio: index.md
  - Manual del Usuario y Programdor: 
    - Requerimientos: userManual/index.md
    - Guía de Inicio: userManual/gettingStarted.md
    - Funcionalidades de DrivingApp: userManual/functionalities.md
    - Configuraciones de DrivingApp: userManual/configurations.md
  - Manual de Instalación y Administración: 
    - Servicios Web de DrivingApp: adminManual/index.md
    - Despliegue de DrivingApp con Docker: adminManual/dockerDeployment.md 

